<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;
use Symfony\Component\HttpFoundation\Request;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Request $request
     * @return Article[]
     */
    public function findArticlesByRequest(Request $request)
    {
        $qb = $this->createQueryBuilder('article');

        if ($tag = $request->get('tag')) {
            $qb
                ->leftJoin('article.tags', 'tag')
                ->andWhere('tag.name = :tag')
                ->setParameter(':tag', $tag);
        }

        return $qb->getQuery()->getResult();
    }
}
